"""add_item_amount

Revision ID: 3ba712a07cc1
Revises: e2293c1c2d2e
Create Date: 2026-04-17 17:00:29.965657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ba712a07cc1'
down_revision: Union[str, Sequence[str], None] = 'e2293c1c2d2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_items', sa.Column('amount', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quotation_items', 'amount')
    # ### end Alembic commands ###
