"""add bill items and manual fields

Revision ID: 489eddb3372a
Revises: 3ba712a07cc1
Create Date: 2026-04-20 13:53:05.379637

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489eddb3372a'
down_revision: Union[str, Sequence[str], None] = '3ba712a07cc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.Integer(), nullable=False),
    sa.Column('item_date', sa.DateTime(), nullable=True),
    sa.Column('event_name', sa.String(length=100), nullable=True),
    sa.Column('venue', sa.String(length=255), nullable=True),
    sa.Column('particulars', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('discount_amount', sa.Float(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bill_items_id'), 'bill_items', ['id'], unique=False)
    op.add_column('bills', sa.Column('customer_name', sa.String(length=100), nullable=True))
    op.add_column('bills', sa.Column('advance_payment', sa.Float(), nullable=False, server_default='0'))
    op.add_column('bills', sa.Column('balance_amount', sa.Float(), nullable=False, server_default='0'))
    op.alter_column('bills', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('bills', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('bills', 'tax_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('bills', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('bills', 'tax_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('bills', 'tax_percent',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('bills', 'subtotal',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('bills', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('bills', 'balance_amount')
    op.drop_column('bills', 'advance_payment')
    op.drop_column('bills', 'customer_name')
    op.drop_index(op.f('ix_bill_items_id'), table_name='bill_items')
    op.drop_table('bill_items')
    # ### end Alembic commands ###
