"""revamp_quotations

Revision ID: 72600b972a70
Revises: b7c6a6c6b7d3
Create Date: 2026-04-17 15:33:42.801416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72600b972a70'
down_revision: Union[str, Sequence[str], None] = 'b7c6a6c6b7d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quotation_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotation_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotation_sections_id'), 'quotation_sections', ['id'], unique=False)
    op.add_column('quotation_items', sa.Column('section_id', sa.Integer(), nullable=False))
    op.add_column('quotation_items', sa.Column('unit_price', sa.Integer(), nullable=True))
    op.add_column('quotation_items', sa.Column('quantity', sa.Float(), nullable=True))
    op.drop_constraint(op.f('quotation_items_quotation_id_fkey'), 'quotation_items', type_='foreignkey')
    op.create_foreign_key(None, 'quotation_items', 'quotation_sections', ['section_id'], ['id'])
    op.drop_column('quotation_items', 'quotation_id')
    op.drop_column('quotations', 'menu_name')
    op.drop_column('quotations', 'amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotations', sa.Column('amount', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('quotations', sa.Column('menu_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('quotation_items', sa.Column('quotation_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'quotation_items', type_='foreignkey')
    op.create_foreign_key(op.f('quotation_items_quotation_id_fkey'), 'quotation_items', 'quotations', ['quotation_id'], ['id'])
    op.drop_column('quotation_items', 'quantity')
    op.drop_column('quotation_items', 'unit_price')
    op.drop_column('quotation_items', 'section_id')
    op.drop_index(op.f('ix_quotation_sections_id'), table_name='quotation_sections')
    op.drop_table('quotation_sections')
    # ### end Alembic commands ###
