"""make_phone_optional

Revision ID: dadbcd932f2d
Revises: 0dcabd0f6e86
Create Date: 2026-04-07 16:56:30.108664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dadbcd932f2d'
down_revision: Union[str, Sequence[str], None] = '0dcabd0f6e86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'customer_phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'customer_phone',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               nullable=False)
    # ### end Alembic commands ###
