"""revamp_quotations

Revision ID: e2293c1c2d2e
Revises: 72600b972a70
Create Date: 2026-04-17 16:07:19.835631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2293c1c2d2e'
down_revision: Union[str, Sequence[str], None] = '72600b972a70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quotation_items', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('quotation_items', 'quantity')
    op.drop_column('quotation_items', 'unit_price')
    op.add_column('quotation_sections', sa.Column('name', sa.String(length=100), nullable=True))
    op.alter_column('quotation_sections', 'amount',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('quotation_sections', 'title')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quotation_sections', sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.alter_column('quotation_sections', 'amount',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('quotation_sections', 'name')
    op.add_column('quotation_items', sa.Column('unit_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('quotation_items', sa.Column('quantity', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('quotation_items', 'section_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
